### ISSUE TITLE
`TypeError: label is not a function` when formatting

### ISSUE THREAD

**Issue by runeh** [alevroub/prettier-plugin-groq#2]
Using version 0.2.3 of the plugin I get this stack trace:

```
TypeError: label is not a function
	at Object.printGROQ [as print] (/my-project-dir/node_modules/prettier-plugin-groq/src/printer.js:37:11)
	at callPluginPrintFunction (/my-project-dir/node_modules/prettier/index.js:14718:18)
	at /my-project-dir/node_modules/prettier/index.js:14649:47
	at Object.printComments (/my-project-dir/node_modules/prettier/index.js:14305:19)
	at printGenerically (/my-project-dir/node_modules/prettier/index.js:14649:22)
	at FastPath.call (/my-project-dir/node_modules/prettier/index.js:14441:20)
	at ß (/my-project-dir/node_modules/prettier-plugin-groq/src/printer.js:5:24)
	at Object.printGROQ [as print] (/my-project-dir/node_modules/prettier-plugin-groq/src/printer.js:152:34)
	at callPluginPrintFunction (/my-project-dir/node_modules/prettier/index.js:14718:18)
	at /my-project-dir/node_modules/prettier/index.js:14649:47
	at Object.printComments (/my-project-dir/node_modules/prettier/index.js:14305:19)
	at printGenerically (/my-project-dir/node_modules/prettier/index.js:14649:22)
	at /my-project-dir/node_modules/prettier/index.js:14487:23
	at FastPath.each (/my-project-dir/node_modules/prettier/index.js:14474:7)
	at FastPath.map (/my-project-dir/node_modules/prettier/index.js:14486:10)
	at ßß (/my-project-dir/node_modules/prettier-plugin-groq/src/printer.js:6:25)
	at Object.printGROQ [as print] (/my-project-dir/node_modules/prettier-plugin-groq/src/printer.js:114:23)
	at callPluginPrintFunction (/my-project-dir/node_modules/prettier/index.js:14718:18)
	at /my-project-dir/node_modules/prettier/index.js:14649:47
	at Object.printComments (/my-project-dir/node_modules/prettier/index.js:14305:19)
	at printGenerically (/my-project-dir/node_modules/prettier/index.js:14649:22)
	at printAstToDoc (/my-project-dir/node_modules/prettier/index.js:14659:13)
	at coreFormat (/my-project-dir/node_modules/prettier/index.js:14910:15)
	at format (/my-project-dir/node_modules/prettier/index.js:15131:14)
	at /my-project-dir/node_modules/prettier/index.js:57542:12
	at Object.format (/my-project-dir/node_modules/prettier/index.js:57562:12)
	at t.default.<anonymous> (/Users/runefh/.vscode/extensions/esbenp.prettier-vscode-8.0.1/dist/extension.js:1:14555)
	at Generator.next (<anonymous>)
	at i (/Users/runefh/.vscode/extensions/esbenp.prettier-vscode-8.0.1/dist/extension.js:1:7003)
```

The query it's trying to clean up is this:

```
{
  "topic": *[_type == "topic" && slug.current == $topicSlug ] {
         publishedAt,
    _id,
    title,
    "slug": slug.current,
    "postCount": count(*[_type == "post" && references(^._id)]),
    "posts": *
    | [_type == "post" && references(^._id)]
    | order(publishedAt desc)
    | [$start...$start+6] {
        _id,
        publishedAt,
        "slug": slug.current,
        body,
        title,
        mainImage
    }
  },
}
```

The query is valid, at least it works in the "vision" plug-in in studio.

**Comment by fabien** [comment]
@runeh I was running into this as well, make sure you are running a recent version of `prettier`. I'm using `2.3.2`.

**Comment by alejandrovrojas** [comment]
@runeh I can see that the plugin is installed locally so as @fabien writes `2.3.2.` should work as expected. In VSCode it's also recommended to set `"prettier.resolveGlobalModules": false` in your settings.json to only use the locally installed instance of prettier and other plugins.
